//! Runtime information cache for Go binaries
//!
//! This module handles caching of Go runtime structure offsets,
//! particularly the runtime.g struct which contains the goroutine ID (goid).
//!
//! The goid offset is extracted dynamically from DWARF debug info during
//! the function signature extraction phase.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::OnceLock;

/// Cached runtime.g struct field offsets
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeGOffsets {
    /// Goroutine ID field offset
    pub goid: u64,

    /// Stack bounds (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stack: Option<u64>,

    /// Stack guard (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stackguard0: Option<u64>,

    /// Pointer to OS thread (m) (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub m: Option<u64>,

    /// Atomic status field (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub atomicstatus: Option<u64>,

    /// All discovered fields
    #[serde(skip_serializing_if = "Option::is_none")]
    pub all_fields: Option<HashMap<String, u64>>,
}

/// Complete runtime information extracted from DWARF
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeInfo {
    /// Go version string (e.g., "go1.21.5")
    pub go_version: String,

    /// Binary path this was extracted from
    pub binary_path: String,

    /// runtime.g struct field offsets
    pub runtime_g_offsets: RuntimeGOffsets,
}

/// Global cache for runtime info (loaded once per binary)
static RUNTIME_INFO: OnceLock<RuntimeGOffsets> = OnceLock::new();

impl RuntimeGOffsets {
    /// Get the goid offset, using cached value if available
    ///
    /// This loads from results/runtime_g_offsets.json (generated during function signature extraction)
    pub fn get_goid_offset() -> u64 {
        RUNTIME_INFO
            .get_or_init(|| {
                // Try loading from pre-extracted DWARF info
                if let Ok(offsets) = Self::load_from_dwarf_cache() {
                    return offsets;
                }

                // Fallback: use default offset with warning
                eprintln!("[RUNTIME-INFO] Warning: runtime_g_offsets.json not found");
                eprintln!("[RUNTIME-INFO] Using default goid offset 152 (may be incorrect)");
                eprintln!("[RUNTIME-INFO] Make sure binary was analyzed with debug symbols");

                RuntimeGOffsets {
                    goid: 152, // Most common offset
                    stack: None,
                    stackguard0: None,
                    m: None,
                    atomicstatus: None,
                    all_fields: None,
                }
            })
            .goid
    }

    /// Load runtime.g offsets from DWARF cache file
    /// This file is generated by scripts/get-funct-arg-types/main --extract-runtime-g
    fn load_from_dwarf_cache() -> Result<Self, Box<dyn std::error::Error>> {
        let cache_path = Path::new("results/runtime_g_offsets.json");

        if !cache_path.exists() {
            return Err("DWARF cache not found".into());
        }

        let content = fs::read_to_string(cache_path)?;
        let runtime_info: RuntimeInfo = serde_json::from_str(&content)?;

        Ok(runtime_info.runtime_g_offsets)
    }
}
